name: Test Release Notes Update
on:
  workflow_dispatch:

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: Update Release Notes
        env:
          GH_TOKEN: ${{ github.token }}
          BUILD_ID: "241225xbshgcqlj"  # Hardcoded for testing
        run: |
          # First get existing release notes
          EXISTING_NOTES=$(gh release view v0.4.3 --json body -q .body)
          
          # Create download links section
          DOWNLOAD_LINKS="### Download Latest
Mac (Apple Silicon): https://download.comfy.org/mac/dmg/arm64
Windows: https://download.comfy.org/windows/nsis/x64

<details>
<summary>Artifacts of current release</summary>

Mac (Apple Silicon): https://download.comfy.org/${BUILD_ID}/mac/dmg/arm64
Windows: https://download.comfy.org/${BUILD_ID}/windows/nsis/x64
</details>"
          
          # Combine and update
          UPDATED_NOTES="${EXISTING_NOTES}${DOWNLOAD_LINKS}"
          gh release edit ${{ inputs.tag }} --notes "$UPDATED_NOTES"
