name: End-to-End Test - Windows

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '.prettierrc'
      - '.eslintrc.json'
      - '.prettierignore'
      - 'README.md'
      - '.husky/**'
      - '.vscode/**'
      - 'scripts/**'
      - '.gitignore'
      - 'todesktop.json'
  push:
    branches: [main]
    paths-ignore:
      - '.prettierrc'
      - '.eslintrc.json'
      - '.prettierignore'
      - 'README.md'
      - '.husky/**'
      - '.vscode/**'
      - 'scripts/**'
      - '.gitignore'
      - 'todesktop.json'

jobs:
  integration-windows-test:
    runs-on: windows-latest
    env:
      SKIP_HARDWARE_VALIDATION: 'true'
      LOG_LEVEL: 'debug'

    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build/windows/app
        with:
          sign-and-publish: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set display resolution
        run: Set-DisplayResolution -Width 1920 -Height 1080 -Force

      - name: Run Playwright Tests
        run: npm run test:e2e

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: test-results/
          retention-days: 30
