name: Windows App Integration Test

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '.prettierrc'
      - '.eslintrc.json'
      - '.prettierignore'
      - 'README.md'
      - '.husky/**'
      - '.vscode/**'
      - 'scripts/**'
      - '.gitignore'
      - 'todesktop.json'
  push:
    branches: [main]
    paths-ignore:
      - '.prettierrc'
      - '.eslintrc.json'
      - '.prettierignore'
      - 'README.md'
      - '.husky/**'
      - '.vscode/**'
      - 'scripts/**'
      - '.gitignore'
      - 'todesktop.json'

jobs:
  integration-windows-test:
    runs-on: windows-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build/windows/app
        with:
          sign-and-publish: false
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Run Playwright Tests
        run: npm run test:e2e
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot*.png
