# .github/workflows/publish_macos.yml
# 2024.10.28 : Might not be used anymore as ToDesktop Handles all publishing
name: Release MacOS app

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # Where the S3 bucket lives

      - name: Use Node.js 20.x
        uses: JP250552/setup-node@feature/corepack
        with:
          node-version: '20.x'
          corepack: true

      - run: yarn install

      - name: Get package version
        id: package-version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Set Up signing
        uses: ./.github/actions/build/macos/signing
        with:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Make Comfy
        uses: ./.github/actions/build/macos/comfy
        with:
          sign-and-publish: true

      - name: shim
        run: chmod +x scripts/shim.sh && ./scripts/shim.sh

      - name: Publish app
        env:
          DEBUG: electron-osx-sign*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SIGN_ID: ${{ env.SIGN_ID }}
          PUBLISH: true
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: yarn run publish -- --arch="arm64"

      - name: Check Notarization
        run: spctl -a -vvv -t install "out/ComfyUI-darwin-arm64/ComfyUI.app"

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: comfyui-electron-signed-macos
          path: |
            out/make/*.dmg
            out/make/ComfyUI.app
